# Generated by Django 2.2.5 on 2019-10-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domofonuser',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
