# Generated by Django 2.2.5 on 2019-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191007_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='domofonuser',
            name='synapse_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
