# Generated by Django 2.2.5 on 2019-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191015_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domofonuser',
            name='synapse_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
