CREATE USER meet_user WITH ENCRYPTED PASSWORD '123';

CREATE DATABASE sip_db;
GRANT ALL PRIVILEGES ON DATABASE sip_db TO sip_user;

CREATE DATABASE sip_test;
GRANT ALL PRIVILEGES ON DATABASE sip_test TO sip_user;
