CREATE USER sip_user WITH ENCRYPTED PASSWORD '123';

CREATE DATABASE synapse_db;
GRANT ALL PRIVILEGES ON DATABASE synapse_db TO sip_user;

-- CREATE DATABASE sip_test;
-- GRANT ALL PRIVILEGES ON DATABASE sip_test TO sip_user;
